#nginx:
#  build: ./nginx
#  volumes:
#    - ./:/usr/share/nginx/html:ro
#  ports:
#    - "8080:80"
foundation:
  build: ./foundationDocker
  volumes:
    - ./:/data
  ports:
    - "8079:8079"
  net: "host"