nginx:
  image: nginx:1.9.6
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  ports:
    - "80:80"
  volumes_from:
    - frontend
  net: "host"
#  command: bash -c "while true; do ls -l /usr/share/nginx/html/; sleep .5; done"

mongo:
  image: mongo:3.0
  command: mongod --smallfiles
  volumes:
    - mongoDbdata:/data/db
  net: "host"

api_server:
  build: ./pythonDocker
  volumes:
    - ./api:/usr/src/app
  ports:
    - "8001:8001"
  net: "host"
  environment:
    MONGO_USERNAME: ""
    MONGO_PASSWORD: ""
    MONGO_DBNAME: development

frontend:
#  build: ./frontendDocker
  image: digitallyseamless/nodejs-bower-grunt
  command: /usr/local/bin/npm start
  working_dir: /data
  volumes:
#    - /usr/share/nginx/html
    - ./:/data
  net: "host"
